output "instance_id" {
  description = "Vultr instance ID."
  value       = vultr_instance.this.id
}

output "main_ip" {
  description = "Primary public IPv4 address."
  value       = vultr_instance.this.main_ip
}

output "v6_main_ip" {
  description = "Primary public IPv6 address (empty when IPv6 is disabled)."
  value       = vultr_instance.this.v6_main_ip
}

output "default_password" {
  description = "Root password generated by Vultr."
  value       = vultr_instance.this.default_password
  sensitive   = true
}
